repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts
  - name: cloudnative-pg
    url: https://cloudnative-pg.github.io/charts
  - name: fluent
    url: https://fluent.github.io/helm-charts

releases:
  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.32.0
    values:
      - ./values/vault.yaml
  - name: cloudnative-pg
    namespace: postgres
    chart: cloudnative-pg/cloudnative-pg
    version: 0.27.1
    wait: true
  - name: postgres
    namespace: postgres
    chart: cloudnative-pg/cluster
    version: 0.6.0
    values:
      - ./values/postgres.yaml
    needs:
      - postgres/cloudnative-pg
  - name: keycloak
    namespace: keycloak
    chart: oci://registry-1.docker.io/cloudpirates/keycloak
    version: 0.16.9
    values:
      - ./values/keycloak.yaml
  - name: opensearch
    namespace: opensearch
    chart: opensearch/opensearch
    version: 3.5.0
    values:
      - ./values/opensearch.yaml
  - name: opensearch-dashboards
    namespace: opensearch
    chart: opensearch/opensearch-dashboards
    version: 3.5.0
    values:
      - ./values/opensearch-dashboards.yaml
    needs:
      - opensearch/opensearch
  - name: fluentd
    namespace: fluentd
    chart: fluent/fluentd
    version: 0.5.3
    values:
      - ./values/fluentd.yaml
